# Generated by Django 5.2.3 on 2025-06-23 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Bill',
            fields=[
                ('bill_number', models.CharField(max_length=20, primary_key=True, serialize=False)),
                ('patient_status', models.CharField(choices=[('Paid', 'Paid'), ('Unpaid', 'Unpaid'), ('Pending', 'Pending')], max_length=10)),
            ],
        ),
    ]
